_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x1c07,0x1cb6,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x1c00,0x1c9a,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x1c0e,0x1cae,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
}
