_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VSUBSS,",
    offsets = "0,",
    addresses = "0x1b86,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VSUBSS,",
    offsets = "0,",
    addresses = "0x1b9f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1b8c,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1b80,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1b98,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "4373,4304,",
    addresses = "0x200b,0x2058,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 73,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VSUBSS,",
    offsets = "0,",
    addresses = "0x1b92,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 22,
    pattern = "SSSSSSSSSSSLLLLLLLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,VMOVSS,MOV,VMOVSS,VMOVSS,VMOVSS,VMOVSS,MOV,MOV,MOV,VMOVSS,VMOVSS,",
    offsets = "-112,-88,-80,-72,-100,-60,-56,-52,-96,-92,-64,-92,-112,-56,-64,-52,-96,-72,-80,-88,-100,-60,",
    addresses = "0x1fbd,0x1fc5,0x1fc9,0x1fcd,0x1fd1,0x1fd6,0x1fdb,0x1fe0,0x1fe5,0x1fea,0x1fef,0x1ff9,0x1ffe,0x2006,0x2013,0x2018,0x2020,0x2025,0x2029,0x202d,0x203a,0x2044,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 120,
    accessed_memory_nooverlap = 60,
    accessed_memory_overlap = 60,
    span = 64,
    head = 0,
    unroll_factor = 1,
  },
}
