_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x1a87,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "SSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,",
    offsets = "0,0,0,",
    addresses = "0x1ab3,0x1ae7,0x1b12,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 16,
    span = 8,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x1a79,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "SSS",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,",
    offsets = "0,0,0,",
    addresses = "0x1aa5,0x1ad9,0x1b04,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 16,
    span = 8,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 12,
    pattern = "LSLLSLLSLLSL",
    opcodes = "VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x1a69,0x1a6d,0x1a7f,0x1a95,0x1a99,0x1aab,0x1ac9,0x1acd,0x1adf,0x1af4,0x1af8,0x1b0a,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 96,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 88,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LSLLSLLSLLSL",
    opcodes = "VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,VADDSD,VMOVSD,VMOVSD,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x1a59,0x1a65,0x1a71,0x1a8d,0x1a91,0x1a9d,0x1ab9,0x1ac5,0x1ad1,0x1aec,0x1af0,0x1afc,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 96,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 88,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
