_group = {
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1bfd,0x1c0b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1b6a,0x1b79,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1bf1,0x1bf7,0x1c06,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1b1c,0x1b2b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1baa,0x1bb0,0x1bbe,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1ad5,0x1ae2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1b5e,0x1b64,0x1b74,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "COMISD,COMISD,COMISD,",
    offsets = "0,8,16,",
    addresses = "0x1aa6,0x1ab2,0x1ae9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1c98,0x1ca5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1c4a,0x1c59,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1b10,0x1b16,0x1b26,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 8,
    pattern = "LLLLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "17799,17727,17649,17573,17502,17425,17347,17276,",
    addresses = "0x1aba,0x1b02,0x1b50,0x1b9c,0x1be3,0x1c30,0x1c7e,0x1cc5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 531,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1ac8,0x1ace,0x1add,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 13,
    pattern = "LLLLLLLLLLLLL",
    opcodes = "COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,",
    offsets = "8,16,24,32,40,48,56,64,72,80,88,96,104,",
    addresses = "0x1afa,0x1b34,0x1b47,0x1b82,0x1b94,0x1bca,0x1bdb,0x1c14,0x1c27,0x1c62,0x1c75,0x1cac,0x1cbd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 104,
    accessed_memory_nooverlap = 104,
    accessed_memory_overlap = 0,
    span = 104,
    head = 0,
    unroll_factor = 13,
  },
  {
    group_size = 16,
    pattern = "LLLLLLLLLLLLLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,8,0,8,0,8,0,8,0,8,0,8,0,8,0,8,",
    addresses = "0x1aa2,0x1aad,0x1ae5,0x1af5,0x1b2f,0x1b41,0x1b7d,0x1b8f,0x1bc6,0x1bd6,0x1c0f,0x1c21,0x1c5d,0x1c6f,0x1ca8,0x1cb8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 112,
    span = 16,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1cdf,0x1ced,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1bb6,0x1bc3,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1cd3,0x1cd9,0x1ce8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1c8c,0x1c92,0x1ca0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1c3e,0x1c44,0x1c54,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
}
