_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x26c8,0x2728,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x26c2,0x272e,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "SUBSD,SUBSD,SUBSD,SUBSD,",
    offsets = "0,0,0,0,",
    addresses = "0x2628,0x2673,0x26e7,0x2734,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "SUBSD,SUBSD,SUBSD,SUBSD,",
    offsets = "0,0,0,0,",
    addresses = "0x2610,0x268e,0x26ce,0x274c,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 4,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x26d3,0x2739,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LSLS",
    opcodes = "ADDSD,MOVSD,ADDSD,MOVSD,",
    offsets = "0,0,0,0,",
    addresses = "0x265f,0x2663,0x271e,0x2723,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x2600,0x266d,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x2606,0x2667,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MULSD,MULSD,MULSD,MULSD,",
    offsets = "14861,14758,14670,14569,",
    addresses = "0x261b,0x2682,0x26d9,0x273f,",
    stride_status = "RIP based value",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 300,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x2615,0x2678,",
    stride_status = "Success",
    stride = 16,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 4,
    pattern = "LSLS",
    opcodes = "ADDSD,MOVSD,ADDSD,MOVSD,",
    offsets = "0,0,0,0,",
    addresses = "0x26ba,0x26be,0x2782,0x2786,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 24,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
