_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "COMISD,COMISD,",
    offsets = "0,8,",
    addresses = "0x2173,0x21c2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 6,
    pattern = "LLLLLL",
    opcodes = "COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,",
    offsets = "8,16,24,32,40,48,",
    addresses = "0x2215,0x2269,0x22bd,0x2311,0x2366,0x23ba,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 0,
    span = 48,
    head = 0,
    unroll_factor = 6,
  },
  {
    group_size = 12,
    pattern = "LSLSLSLSLSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x2230,0x2258,0x2285,0x22ad,0x22d8,0x2300,0x232d,0x2355,0x2382,0x23aa,0x23d5,0x23fd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 96,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 88,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 6,
    pattern = "LLLLLL",
    opcodes = "COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,",
    offsets = "0,0,0,0,0,0,",
    addresses = "0x2228,0x227d,0x22d0,0x2325,0x237a,0x23cd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 40,
    span = 8,
    head = 0,
    unroll_factor = 6,
  },
  {
    group_size = 16,
    pattern = "LSLSLSLSLSLSLSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,",
    addresses = "0x2190,0x219e,0x21e3,0x21f1,0x2236,0x2244,0x228b,0x2299,0x22de,0x22ec,0x2333,0x2341,0x2388,0x2396,0x23db,0x23e9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 120,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LSLSLSLSLSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x224b,0x225e,0x22a0,0x22b3,0x22f3,0x2306,0x2348,0x235b,0x239d,0x23b0,0x23f0,0x2403,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 96,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 88,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x21dd,0x2205,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 8,
    pattern = "LLLLLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,0,0,0,0,0,0,0,",
    addresses = "0x216e,0x21be,0x2211,0x2264,0x22b9,0x230c,0x2361,0x23b6,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 56,
    span = 8,
    head = 0,
    unroll_factor = 8,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x218a,0x21b2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 16,
    pattern = "LSLSLSLSLSLSLSLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,-8,",
    addresses = "0x2197,0x21ab,0x21ea,0x21fe,0x223d,0x2251,0x2292,0x22a6,0x22e5,0x22f9,0x233a,0x234e,0x238f,0x23a3,0x23e2,0x23f6,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 120,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x21a5,0x21b8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "COMISD,",
    offsets = "0,",
    addresses = "0x21d5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVSD,MOVSD,",
    offsets = "0,0,",
    addresses = "0x21f8,0x220b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 8,
    pattern = "LLLLLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "-8,-8,-8,-8,-8,-8,-8,-8,",
    addresses = "0x217b,0x21ce,0x2221,0x2276,0x22c9,0x231e,0x2373,0x23c6,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 56,
    span = 8,
    head = 0,
    unroll_factor = 8,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "COMISD,",
    offsets = "0,",
    addresses = "0x2182,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
