_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x84b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x85e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 10,
    pattern = "LLSLSLLLLS",
    opcodes = "MOV,CMP,MOV,MOV,MOV,MOV,MOV,MOV,MOV,ADD,",
    offsets = "-8,-28,-4,-4,-4,-12,-24,-8,-4,-8,",
    addresses = "0x864,0x867,0x827,0x82a,0x834,0x837,0x844,0x84e,0x85b,0x860,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 44,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 20,
    span = 28,
    head = 0,
    unroll_factor = 1,
  },
}
