_group = {
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1763,0x1771,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x167b,0x1680,0x1690,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1881,0x1886,0x1895,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1834,0x1839,0x1849,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x17ed,0x17f2,0x1801,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x183f,0x184d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x171a,0x1727,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 16,
    pattern = "LLLLLLLLLLLLLLLL",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,8,0,8,0,8,0,8,0,8,0,8,0,8,0,8,",
    addresses = "0x1651,0x165e,0x1698,0x16aa,0x16e3,0x16f3,0x172a,0x173a,0x1775,0x1787,0x17c1,0x17d1,0x1808,0x1818,0x1851,0x1863,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 112,
    span = 16,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x188c,0x1899,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x1686,0x1694,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 13,
    pattern = "LLLLLLLLLLLLL",
    opcodes = "COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,COMISD,",
    offsets = "8,16,24,32,40,48,56,64,72,80,88,96,104,",
    addresses = "0x16b0,0x16e7,0x16f8,0x172e,0x1740,0x177a,0x178d,0x17c5,0x17d6,0x180c,0x181d,0x1856,0x1869,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 104,
    accessed_memory_nooverlap = 104,
    accessed_memory_overlap = 0,
    span = 104,
    head = 0,
    unroll_factor = 13,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x1758,0x175d,0x176d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 8,
    pattern = "LLLLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "18900,18824,18753,18680,18603,18531,18460,18383,",
    addresses = "0x166d,0x16b9,0x1700,0x1749,0x1796,0x17de,0x1825,0x1872,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 525,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x17a5,0x17aa,0x17b9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x17f8,0x1805,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x16d3,0x16e0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x17b0,0x17bd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x170f,0x1714,0x1723,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLS",
    opcodes = "MOVSD,MOVSD,MOVUPS,",
    offsets = "0,8,0,",
    addresses = "0x16c7,0x16cd,0x16db,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "COMISD,COMISD,COMISD,",
    offsets = "0,8,16,",
    addresses = "0x1656,0x1664,0x169d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 24,
    accessed_memory_nooverlap = 24,
    accessed_memory_overlap = 0,
    span = 24,
    head = 0,
    unroll_factor = 3,
  },
}
