_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVDQU,",
    offsets = "0,",
    addresses = "0x2a8c,",
    stride_status = "Iteration not constant",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVDQU,",
    offsets = "0,",
    addresses = "0x2a56,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 16,
    pattern = "SSSLLLSSSLLSSSLL",
    opcodes = "MOVSD,MOVAPS,MOVAPS,MULSD,MULSD,MOVAPD,MOVAPS,MOVAPS,MOVAPS,MOVSD,MOVAPD,MOVAPS,MOVAPS,MOVAPS,MOVSD,MOVAPD,",
    offsets = "0,32,16,0,0,32,16,32,0,0,32,32,16,0,0,32,",
    addresses = "0x2a4a,0x2a5b,0x2a60,0x2a6a,0x2a77,0x2a86,0x2a92,0x2a97,0x2a9c,0x2aa0,0x2aca,0x2ad4,0x2ad9,0x2ade,0x2ae2,0x2b05,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 216,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 168,
    span = 48,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOVDQU,MOVUPS,",
    offsets = "0,0,",
    addresses = "0x2ad0,0x2b15,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 16,
    span = 16,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "MOV,MOV,ADD,CMP,",
    offsets = "13817,13762,13702,13599,",
    addresses = "0x2a40,0x2a7f,0x2ac3,0x2b0f,",
    stride_status = "RIP based value",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 28,
    accessed_memory_nooverlap = 28,
    accessed_memory_overlap = 0,
    span = 226,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 14,
    pattern = "LSLSLSLLSLSLLS",
    opcodes = "MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,MOVSD,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x2a65,0x2a6e,0x2a72,0x2a7b,0x2aa4,0x2aad,0x2ab1,0x2ab6,0x2abf,0x2ae6,0x2aef,0x2af3,0x2af8,0x2b01,",
    stride_status = "Not Analyzed",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 112,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 104,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
